name: Goshname

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: first loc
      run: |
        pip install -r req.txt
        python goshne.py
      env:
        LOC_NAME: ${{ secrets.LOC1 }}
        LAT: ${{ secrets.LAT }}
        LONG: ${{ secrets.LONG }}
        CHATID: ${{ secrets.CHATID }}
        TOKEN: ${{ secrets.TOKEN }}
    - name: second loc
      run: |
        pip install -r req.txt
        python goshne.py
      env:
        LOC_NAME: ${{ secrets.LOC2 }}
        LAT: ${{ secrets.LAT2 }}
        LONG: ${{ secrets.LONG2 }}
        CHATID: ${{ secrets.CHATID }}
        TOKEN: ${{ secrets.TOKEN }}
    - name: third loc
      run: |
        pip install -r req.txt
        python goshne.py
      env:
        LOC_NAME: ${{ secrets.LOC3 }}
        LAT: ${{ secrets.LAT3 }}
        LONG: ${{ secrets.LONG3 }}
        CHATID: ${{ secrets.CHATID }}
        TOKEN: ${{ secrets.TOKEN }}
    - name: push changes to remote
      run: |
        git config --global user.name "lilcheti"
        git config --global user.email "farbod@tokhmi.xyz"
        git pull
        git add -A
        if [ -z "$(git status --porcelain)" ]; then 
          echo "No changes"
        else 
          git commit -m "updated the data"
          git push
        fi
